//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.08 at 08:14:18 PM CEST 
//


package com.inttra.mercury.billoflading.model;

public enum ReferenceNameType {

    BILL_OF_LADING_NUMBER("BillOfLadingNumber"),

    BOOKING_NUMBER("BookingNumber"),

    BROKER_REFERENCE_NUMBER("BrokerReferenceNumber"),

    CONSIGNEE_ORDER_NUMBER("ConsigneeOrderNumber"),

    CONTRACT_NUMBER("ContractNumber"),

    CUSTOMER_SHIPMENT_IDENTIFIER("CustomerShipmentIdentifier"),

    EXPORTER_REFERENCE_NUMBER("ExporterReferenceNumber"),

    FREIGHT_FORWARDER_REFERENCE("FreightForwarderReference"),

    FEDERAL_MARITIME_COM_NUMBER("FederalMaritimeComNumber"),

    HOUSE_BILL("HouseBill"),

    INVOICE_NUMBER("InvoiceNumber"),

    PURCHASE_ORDER_NUMBER("PurchaseOrderNumber"),

    SHIPMENT_ID("ShipmentID"),

    SHIPPER_IDENTIFYING_NUMBER("ShipperIdentifyingNumber"),

    TARIFF_NUMBER("TariffNumber"),

    TRANSACTION_REFERENCE_NUMBER("TransactionReferenceNumber");
    private final String value;

    ReferenceNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReferenceNameType fromValue(String v) {
        for (ReferenceNameType c: ReferenceNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
